default_platform(:ios)

platform :ios do
  desc "Build an Ad Hoc IPA (for installing on registered devices)"
  lane :adhoc do
    setup_ci

    # Expect signing assets to be installed by CI steps.
    app_id = ENV.fetch('IOS_BUNDLE_ID')
    profile_name = "ios" # Provisioning Profile Name (not filename)

    build_app(
      workspace: "ios/StackPerformance.xcworkspace",
      scheme: "StackPerformance",
      configuration: "Release",
      export_method: "ad-hoc",
      output_directory: "./artifacts",
      output_name: "StackPerformance.ipa",
      export_options: {
        provisioningProfiles: {
          app_id => profile_name
        }
      },
      xcargs: [
        "DEVELOPMENT_TEAM=#{ENV.fetch('APPLE_TEAM_ID')}",
        "CODE_SIGN_STYLE=Manual",
        "PROVISIONING_PROFILE_SPECIFIER=#{profile_name}"
      ].join(" ")
    )
  end
end
